### ISSUE TITLE
POSTPROCESSOR Thread get Stuck (directory is already being processed)

### ISSUE THREAD

**Issue by kyuuk** [SickChill/SickChill#5098]
Branch : master
Commit:  42ebd22
OS: Linux-4.14.71-v7+-armv7l-with-debian-9.4
Browser: 
What you did: /
What happened: sometimes POSTPROCESSOR Thread get stuck and new PostProcessing tasks are not performed until i reboot SickChill
What you expected: /
Logs:
```
2018-10-17 09:51:04 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-10-17 09:51:04 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-10-17 09:41:04 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-10-17 09:36:29 INFO SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2018-10-17 09:34:10 INFO SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2018-10-17 09:34:08 INFO DAILYSEARCHER :: No new released episodes found ...
2018-10-17 09:34:08 INFO DAILYSEARCHER :: Searching for new released episodes ...
2018-10-17 09:31:04 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-10-17 09:21:03 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-10-17 09:11:02 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-10-17 09:04:51 INFO FINDSUBTITLES :: No subtitles to download
2018-10-17 09:04:51 INFO FINDSUBTITLES :: Checking for missed subtitles
2018-10-17 09:01:02 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-10-17 08:51:01 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-10-17 08:41:01 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-10-17 08:36:14 INFO SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2018-10-17 08:34:08 INFO SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2018-10-17 08:34:07 INFO DAILYSEARCHER :: No new released episodes found ...
2018-10-17 08:34:07 INFO DAILYSEARCHER :: Searching for new released episodes ...
2018-10-17 08:31:00 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-10-17 08:21:00 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-10-17 08:10:59 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-10-17 08:04:50 INFO FINDSUBTITLES :: No subtitles to download
2018-10-17 08:04:50 INFO FINDSUBTITLES :: Checking for missed subtitles
2018-10-17 08:00:59 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-10-17 07:50:58 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-10-17 07:40:58 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-10-17 07:36:14 INFO SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2018-10-17 07:34:07 INFO SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2018-10-17 07:34:07 INFO DAILYSEARCHER :: No new released episodes found ...
2018-10-17 07:34:07 INFO DAILYSEARCHER :: Searching for new released episodes ...
2018-10-17 07:30:57 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-10-17 07:20:56 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-10-17 07:10:56 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-10-17 07:04:50 INFO FINDSUBTITLES :: No subtitles to download
2018-10-17 07:04:50 INFO FINDSUBTITLES :: Checking for missed subtitles
2018-10-17 07:00:55 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-10-17 06:50:55 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-10-17 06:40:54 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-10-17 06:37:24 INFO SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2018-10-17 06:34:52 INFO SEARCHQUEUE-DAILY-SEARCH :: [HorribleSubs] :: Request failed: HTTPConnectionPool(host='horriblesubs.info', port=80): Read timed out.
2018-10-17 06:34:11 INFO SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2018-10-17 06:34:07 INFO DAILYSEARCHER :: No new released episodes found ...
2018-10-17 06:34:06 INFO DAILYSEARCHER :: Searching for new released episodes ...
2018-10-17 06:30:54 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-10-17 06:20:53 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-10-17 06:12:10 INFO POSTPROCESSOR-AUTO :: Sending discord message to url: https://discordapp.com/api/webhooks/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
2018-10-17 06:12:10 INFO POSTPROCESSOR-AUTO :: Sending discord message: Finished Download: To Aru Majutsu no Index - 3x01 - En crise - 720p HDTV
2018-10-17 06:10:57 INFO POSTPROCESSOR-AUTO :: This download is marked a priority download so I'm going to replace an existing file if I find one
2018-10-17 06:10:56 INFO POSTPROCESSOR-AUTO :: Processing /home/****/Downloads/[HorribleSubs] Toaru Majutsu no Index III - 01 [720p].mkv (None)
```

**Comment by kyuuk** [comment]
Thank you for the reply, and sorry for mylate reply but it didn't happen from that time, so it was somehow fixed by another update i think...

**Comment by kyuuk** [comment]
hello again, it seems that the bug is sill here, so here is the debug log i got for the PostProcessor
```
2018-12-01 22:19:07 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-12-01 22:19:07 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 22:09:06 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-12-01 22:09:06 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 21:59:06 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-12-01 21:59:05 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 21:49:05 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-12-01 21:49:05 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 21:39:04 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-12-01 21:39:04 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 21:29:04 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-12-01 21:29:04 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 21:19:03 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-12-01 21:19:03 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 21:09:02 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-12-01 21:09:02 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 20:59:02 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-12-01 20:59:02 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 20:49:01 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-12-01 20:49:01 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 20:39:00 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-12-01 20:39:00 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 20:28:59 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-12-01 20:28:59 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 20:18:59 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-12-01 20:18:59 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 20:08:58 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-12-01 20:08:58 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 19:58:57 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-12-01 19:58:57 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 19:48:57 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-12-01 19:48:57 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 19:38:56 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-12-01 19:38:56 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 19:29:49 INFO POSTPROCESSOR-AUTO :: Sending discord message to url: https://discordapp.com/api/webhooks/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
2018-12-01 19:29:49 INFO POSTPROCESSOR-AUTO :: Sending discord message: Finished Download: Radiant - 1x09 - À la poursuite de l’hérésie - 720p HDTV
2018-12-01 19:29:49 DEBUG POSTPROCESSOR-AUTO :: Notification for NMJ scan update not enabled, skipping this notification
2018-12-01 19:29:49 DEBUG POSTPROCESSOR-AUTO :: formatting pattern: %SN - %Sx%0E - %EN - %QN -> Radiant - 1x09 - À la poursuite de l’hérésie - 720p HDTV
2018-12-01 19:29:49 DEBUG POSTPROCESSOR-AUTO :: Using cached parse result for: [HorribleSubs] Radiant - 09 [720p]
2018-12-01 19:29:49 DEBUG POSTPROCESSOR-AUTO :: Parsed /media/syno/Animes/enCours/Radiant/Season_01/Radiant_S01E09_-_À la poursuite de l’hérésie into Season - S01E09 [ABD: False] [ANIME: False] [whichReg: [u'anime_SxxExx', u'anime_bare']]
2018-12-01 19:29:49 DEBUG POSTPROCESSOR-AUTO :: Setter sets location to /media/syno/Animes/enCours/Radiant/Season_01/Radiant_S01E09_-_À la poursuite de l’hérésie.mkv
2018-12-01 19:29:06 DEBUG POSTPROCESSOR-AUTO :: Moving file from /home/****/Downloads/[HorribleSubs] Radiant - 09 [720p].mkv to /media/syno/Animes/enCours/Radiant/Season_01/Radiant_S01E09_-_À la poursuite de l’hérésie.mkv
2018-12-01 19:29:06 DEBUG POSTPROCESSOR-AUTO :: No associated files for /home/****/Downloads/[HorribleSubs] Radiant - 09 [720p].mkv were found during this pass
2018-12-01 19:29:05 DEBUG POSTPROCESSOR-AUTO :: anidb: Added the episode to anidb
2018-12-01 19:29:05 DEBUG POSTPROCESSOR-AUTO :: anidb: NetIO > 'MYLISTADD tag=T001&state=1&ed2k=4fa46fdd79ca7a84ce07de9de7c239a6&s=FuRI8&size=326987030'
2018-12-01 19:29:05 DEBUG POSTPROCESSOR-AUTO :: anidb: handling(1-2) command MYLISTADD
2018-12-01 19:29:03 DEBUG POSTPROCESSOR-AUTO :: anidb: Calculating the ed2k. Please wait...
2018-12-01 19:29:03 DEBUG POSTPROCESSOR-AUTO :: Adding the file to the anidb mylist
2018-12-01 19:29:03 DEBUG POSTPROCESSOR-AUTO :: anidb: NetIO > sensitive data is not logged!
2018-12-01 19:29:01 DEBUG POSTPROCESSOR-AUTO :: anidb: handling(0-2) command AUTH
2018-12-01 19:29:01 DEBUG POSTPROCESSOR-AUTO :: anidb: Starting thread now...
2018-12-01 19:29:01 DEBUG POSTPROCESSOR-AUTO :: anidb: You wanted to keep this thing alive!
2018-12-01 19:29:01 DEBUG POSTPROCESSOR-AUTO :: anidb: ok2
2018-12-01 19:29:01 DEBUG POSTPROCESSOR-AUTO :: anidb: ok1
2018-12-01 19:29:01 DEBUG POSTPROCESSOR-AUTO :: Checking if the path /media/syno/Animes/enCours/Radiant/Season_01 already exists
2018-12-01 19:29:01 DEBUG POSTPROCESSOR-AUTO :: Destination folder for this episode: /media/syno/Animes/enCours/Radiant/Season_01
2018-12-01 19:29:01 DEBUG POSTPROCESSOR-AUTO :: formatting pattern: Season_%0S -> Season_01
2018-12-01 19:29:01 DEBUG POSTPROCESSOR-AUTO :: Using cached parse result for: [HorribleSubs] Radiant - 09 [720p]
2018-12-01 19:29:01 DEBUG POSTPROCESSOR-AUTO :: formatting pattern: %SN_S%0SE%0E_-_%EN -> Radiant_S01E09_-_À la poursuite de l’hérésie
2018-12-01 19:29:00 DEBUG POSTPROCESSOR-AUTO :: Using cached parse result for: [HorribleSubs] Radiant - 09 [720p]
2018-12-01 19:29:00 DEBUG POSTPROCESSOR-AUTO :: Folder name (Downloads) appears to be a valid release name. Using it.
2018-12-01 19:28:59 DEBUG POSTPROCESSOR-AUTO :: Found release name [HorribleSubs] Radiant - 09 [720p]
2018-12-01 19:28:59 DEBUG POSTPROCESSOR-AUTO :: Trying to determine free space on the destination drive
2018-12-01 19:28:59 INFO POSTPROCESSOR-AUTO :: This download is marked a priority download so I'm going to replace an existing file if I find one
2018-12-01 19:28:59 DEBUG POSTPROCESSOR-AUTO :: There is no existing file so there's no worries about replacing it
2018-12-01 19:28:59 DEBUG POSTPROCESSOR-AUTO :: Is ep a priority download: True
2018-12-01 19:28:59 DEBUG POSTPROCESSOR-AUTO :: SR snatched this episode and it is not processed before
2018-12-01 19:28:59 DEBUG POSTPROCESSOR-AUTO :: Quality of the episode we're processing: 720p HDTV
2018-12-01 19:28:59 DEBUG POSTPROCESSOR-AUTO :: Snatch history had a quality in it, using that: 720p HDTV
2018-12-01 19:28:59 DEBUG POSTPROCESSOR-AUTO :: Retrieving episode object for 1x9
2018-12-01 19:28:59 DEBUG POSTPROCESSOR-AUTO :: Parsed [HorribleSubs] Radiant - 09 [720p] into Radiant - S01E09 [ABS: [9]] [ANIME VER: 1] [GROUP: HorribleSubs] [ABD: False] [ANIME: True] [whichReg: [u'anime_horriblesubs']]
2018-12-01 19:28:59 DEBUG POSTPROCESSOR-AUTO :: Found episode by absolute number 9 which is S01E09
2018-12-01 19:28:58 DEBUG POSTPROCESSOR-AUTO :: Analyzing name [HorribleSubs] Radiant - 09 [720p].mkv
2018-12-01 19:28:58 INFO POSTPROCESSOR-AUTO :: Processing /home/****/Downloads/[HorribleSubs] Radiant - 09 [720p].mkv (None)
2018-12-01 19:28:58 DEBUG POSTPROCESSOR-AUTO :: Parsed [HorribleSubs] Radiant - 09 [720p].mkv into Radiant - S01E09 [ABS: [9]] [ANIME VER: 1] [GROUP: HorribleSubs] [ABD: False] [ANIME: True] [whichReg: [u'anime_horriblesubs']]
2018-12-01 19:28:58 DEBUG POSTPROCESSOR-AUTO :: Found episode by absolute number 9 which is S01E09
2018-12-01 19:28:56 DEBUG POSTPROCESSOR-AUTO :: Processing folder /home/****/Downloads
2018-12-01 19:28:56 INFO POSTPROCESSOR-AUTO :: Processing /home/****/Downloads
2018-12-01 19:28:56 DEBUG POSTPROCESSOR-AUTO :: Processing in folder /home/****/Downloads
2018-12-01 19:28:56 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /home/****/Downloads
2018-12-01 19:28:55 INFO POSTPROCESSOR :: Auto post processing task for /home/****/Downloads was added to the queue
2018-12-01 19:28:55 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 19:18:56 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /home/****/Downloads completed
2018-12-01 19:18:56 INFO POSTPROCESSOR-AUTO :: Successfully processed
2018-12-01 19:18:56 DEBUG POSTPROCESSOR-AUTO :: /home/****/Downloads : No processable items found in folder
2018-12-01 19:18:55 DEBUG POSTPROCESSOR-AUTO :: Processing folder /home/****/Downloads
2018-12-01 19:18:55 INFO POSTPROCESSOR-AUTO :: Processing /home/****/Downloads
2018-12-01 19:18:55 DEBUG POSTPROCESSOR-AUTO :: Processing in folder /home/****/Downloads
2018-12-01 19:18:55 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /home/****/Downloads
2018-12-01 19:18:54 INFO POSTPROCESSOR :: Auto post processing task for /home/****/Downloads was added to the queue
2018-12-01 19:18:54 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 19:08:55 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /home/****/Downloads completed
2018-12-01 19:08:55 INFO POSTPROCESSOR-AUTO :: Successfully processed
2018-12-01 19:08:55 DEBUG POSTPROCESSOR-AUTO :: /home/****/Downloads : No processable items found in folder
2018-12-01 19:08:55 DEBUG POSTPROCESSOR-AUTO :: Processing folder /home/****/Downloads
2018-12-01 19:08:55 INFO POSTPROCESSOR-AUTO :: Processing /home/****/Downloads
2018-12-01 19:08:55 DEBUG POSTPROCESSOR-AUTO :: Processing in folder /home/****/Downloads
2018-12-01 19:08:55 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /home/****/Downloads
2018-12-01 19:08:54 INFO POSTPROCESSOR :: Auto post processing task for /home/****/Downloads was added to the queue
2018-12-01 19:08:54 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 18:58:55 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /home/****/Downloads completed
2018-12-01 18:58:55 INFO POSTPROCESSOR-AUTO :: Successfully processed
2018-12-01 18:58:55 DEBUG POSTPROCESSOR-AUTO :: /home/****/Downloads : No processable items found in folder
2018-12-01 18:58:54 DEBUG POSTPROCESSOR-AUTO :: Processing folder /home/****/Downloads
2018-12-01 18:58:54 INFO POSTPROCESSOR-AUTO :: Processing /home/****/Downloads
2018-12-01 18:58:54 DEBUG POSTPROCESSOR-AUTO :: Processing in folder /home/****/Downloads
2018-12-01 18:58:54 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /home/****/Downloads
2018-12-01 18:58:53 INFO POSTPROCESSOR :: Auto post processing task for /home/****/Downloads was added to the queue
2018-12-01 18:58:53 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 18:48:54 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /home/****/Downloads completed
2018-12-01 18:48:54 INFO POSTPROCESSOR-AUTO :: Successfully processed
2018-12-01 18:48:54 DEBUG POSTPROCESSOR-AUTO :: /home/****/Downloads : No processable items found in folder
2018-12-01 18:48:53 DEBUG POSTPROCESSOR-AUTO :: Processing folder /home/****/Downloads
2018-12-01 18:48:53 INFO POSTPROCESSOR-AUTO :: Processing /home/****/Downloads
2018-12-01 18:48:53 DEBUG POSTPROCESSOR-AUTO :: Processing in folder /home/****/Downloads
2018-12-01 18:48:53 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /home/****/Downloads
2018-12-01 18:48:52 INFO POSTPROCESSOR :: Auto post processing task for /home/****/Downloads was added to the queue
2018-12-01 18:48:52 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 18:38:53 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /home/****/Downloads completed
2018-12-01 18:38:53 INFO POSTPROCESSOR-AUTO :: Successfully processed
2018-12-01 18:38:53 DEBUG POSTPROCESSOR-AUTO :: /home/****/Downloads : No processable items found in folder
2018-12-01 18:38:53 DEBUG POSTPROCESSOR-AUTO :: Processing folder /home/****/Downloads
2018-12-01 18:38:53 INFO POSTPROCESSOR-AUTO :: Processing /home/****/Downloads
2018-12-01 18:38:53 DEBUG POSTPROCESSOR-AUTO :: Processing in folder /home/****/Downloads
2018-12-01 18:38:53 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /home/****/Downloads
2018-12-01 18:38:51 INFO POSTPROCESSOR :: Auto post processing task for /home/****/Downloads was added to the queue
2018-12-01 18:38:51 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 18:28:52 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /home/****/Downloads completed
2018-12-01 18:28:52 INFO POSTPROCESSOR-AUTO :: Successfully processed
2018-12-01 18:28:52 DEBUG POSTPROCESSOR-AUTO :: /home/****/Downloads : No processable items found in folder
2018-12-01 18:28:52 DEBUG POSTPROCESSOR-AUTO :: Processing folder /home/****/Downloads
2018-12-01 18:28:52 INFO POSTPROCESSOR-AUTO :: Processing /home/****/Downloads
2018-12-01 18:28:52 DEBUG POSTPROCESSOR-AUTO :: Processing in folder /home/****/Downloads
2018-12-01 18:28:52 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /home/****/Downloads
2018-12-01 18:28:51 INFO POSTPROCESSOR :: Auto post processing task for /home/****/Downloads was added to the queue
2018-12-01 18:28:51 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 18:18:52 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /home/****/Downloads completed
2018-12-01 18:18:51 INFO POSTPROCESSOR-AUTO :: Successfully processed
2018-12-01 18:18:51 DEBUG POSTPROCESSOR-AUTO :: /home/****/Downloads : No processable items found in folder
2018-12-01 18:18:51 DEBUG POSTPROCESSOR-AUTO :: Processing folder /home/****/Downloads
2018-12-01 18:18:51 INFO POSTPROCESSOR-AUTO :: Processing /home/****/Downloads
2018-12-01 18:18:51 DEBUG POSTPROCESSOR-AUTO :: Processing in folder /home/****/Downloads
2018-12-01 18:18:51 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /home/****/Downloads
2018-12-01 18:18:50 INFO POSTPROCESSOR :: Auto post processing task for /home/****/Downloads was added to the queue
2018-12-01 18:18:50 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 18:08:51 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /home/****/Downloads completed
2018-12-01 18:08:51 INFO POSTPROCESSOR-AUTO :: Successfully processed
2018-12-01 18:08:51 DEBUG POSTPROCESSOR-AUTO :: /home/****/Downloads : No processable items found in folder
2018-12-01 18:08:50 DEBUG POSTPROCESSOR-AUTO :: Processing folder /home/****/Downloads
2018-12-01 18:08:50 INFO POSTPROCESSOR-AUTO :: Processing /home/****/Downloads
2018-12-01 18:08:50 DEBUG POSTPROCESSOR-AUTO :: Processing in folder /home/****/Downloads
2018-12-01 18:08:50 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /home/****/Downloads
2018-12-01 18:08:50 INFO POSTPROCESSOR :: Auto post processing task for /home/****/Downloads was added to the queue
2018-12-01 18:08:50 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 17:58:50 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /home/****/Downloads completed
2018-12-01 17:58:50 INFO POSTPROCESSOR-AUTO :: Successfully processed
2018-12-01 17:58:50 DEBUG POSTPROCESSOR-AUTO :: /home/****/Downloads : No processable items found in folder
2018-12-01 17:58:49 DEBUG POSTPROCESSOR-AUTO :: Processing folder /home/****/Downloads
2018-12-01 17:58:49 INFO POSTPROCESSOR-AUTO :: Processing /home/****/Downloads
2018-12-01 17:58:49 DEBUG POSTPROCESSOR-AUTO :: Processing in folder /home/****/Downloads
2018-12-01 17:58:49 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /home/****/Downloads
2018-12-01 17:58:49 INFO POSTPROCESSOR :: Auto post processing task for /home/****/Downloads was added to the queue
2018-12-01 17:58:49 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 17:48:50 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /home/****/Downloads completed
2018-12-01 17:48:50 INFO POSTPROCESSOR-AUTO :: Successfully processed
2018-12-01 17:48:50 DEBUG POSTPROCESSOR-AUTO :: /home/****/Downloads : No processable items found in folder
2018-12-01 17:48:49 DEBUG POSTPROCESSOR-AUTO :: Processing folder /home/****/Downloads
2018-12-01 17:48:49 INFO POSTPROCESSOR-AUTO :: Processing /home/****/Downloads
2018-12-01 17:48:49 DEBUG POSTPROCESSOR-AUTO :: Processing in folder /home/****/Downloads
2018-12-01 17:48:49 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /home/****/Downloads
2018-12-01 17:48:48 INFO POSTPROCESSOR :: Auto post processing task for /home/****/Downloads was added to the queue
2018-12-01 17:48:48 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 17:38:49 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /home/****/Downloads completed
2018-12-01 17:38:49 INFO POSTPROCESSOR-AUTO :: Successfully processed
2018-12-01 17:38:49 DEBUG POSTPROCESSOR-AUTO :: /home/****/Downloads : No processable items found in folder
2018-12-01 17:38:48 DEBUG POSTPROCESSOR-AUTO :: Processing folder /home/****/Downloads
2018-12-01 17:38:48 INFO POSTPROCESSOR-AUTO :: Processing /home/****/Downloads
2018-12-01 17:38:48 DEBUG POSTPROCESSOR-AUTO :: Processing in folder /home/****/Downloads
2018-12-01 17:38:48 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /home/****/Downloads
2018-12-01 17:38:48 INFO POSTPROCESSOR :: Auto post processing task for /home/****/Downloads was added to the queue
2018-12-01 17:38:48 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 17:28:48 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /home/****/Downloads completed
2018-12-01 17:28:48 INFO POSTPROCESSOR-AUTO :: Successfully processed
2018-12-01 17:28:48 DEBUG POSTPROCESSOR-AUTO :: /home/****/Downloads : No processable items found in folder
2018-12-01 17:28:47 DEBUG POSTPROCESSOR-AUTO :: Processing folder /home/****/Downloads
2018-12-01 17:28:47 INFO POSTPROCESSOR-AUTO :: Processing /home/****/Downloads
2018-12-01 17:28:47 DEBUG POSTPROCESSOR-AUTO :: Processing in folder /home/****/Downloads
2018-12-01 17:28:47 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /home/****/Downloads
2018-12-01 17:28:47 INFO POSTPROCESSOR :: Auto post processing task for /home/****/Downloads was added to the queue
2018-12-01 17:28:47 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 17:18:51 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /home/****/Downloads completed
2018-12-01 17:18:51 INFO POSTPROCESSOR-AUTO :: Successfully processed
2018-12-01 17:18:51 DEBUG POSTPROCESSOR-AUTO :: /home/****/Downloads : No processable items found in folder
2018-12-01 17:18:51 DEBUG POSTPROCESSOR-AUTO :: Processing folder /home/****/Downloads
2018-12-01 17:18:51 INFO POSTPROCESSOR-AUTO :: Processing /home/****/Downloads
2018-12-01 17:18:51 DEBUG POSTPROCESSOR-AUTO :: Processing in folder /home/****/Downloads
2018-12-01 17:18:51 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /home/****/Downloads
2018-12-01 17:18:46 INFO POSTPROCESSOR :: Auto post processing task for /home/****/Downloads was added to the queue
2018-12-01 17:18:46 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 17:08:51 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /home/****/Downloads completed
2018-12-01 17:08:51 INFO POSTPROCESSOR-AUTO :: Successfully processed
2018-12-01 17:08:51 DEBUG POSTPROCESSOR-AUTO :: /home/****/Downloads : No processable items found in folder
2018-12-01 17:08:50 DEBUG POSTPROCESSOR-AUTO :: Processing folder /home/****/Downloads
2018-12-01 17:08:50 INFO POSTPROCESSOR-AUTO :: Processing /home/****/Downloads
2018-12-01 17:08:50 DEBUG POSTPROCESSOR-AUTO :: Processing in folder /home/****/Downloads
2018-12-01 17:08:50 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /home/****/Downloads
2018-12-01 17:08:45 INFO POSTPROCESSOR :: Auto post processing task for /home/****/Downloads was added to the queue
2018-12-01 17:08:45 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 16:58:50 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /home/****/Downloads completed
2018-12-01 16:58:50 INFO POSTPROCESSOR-AUTO :: Successfully processed
2018-12-01 16:58:50 DEBUG POSTPROCESSOR-AUTO :: /home/****/Downloads : No processable items found in folder
2018-12-01 16:58:49 DEBUG POSTPROCESSOR-AUTO :: Processing folder /home/****/Downloads
2018-12-01 16:58:49 INFO POSTPROCESSOR-AUTO :: Processing /home/****/Downloads
2018-12-01 16:58:49 DEBUG POSTPROCESSOR-AUTO :: Processing in folder /home/****/Downloads
2018-12-01 16:58:49 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /home/****/Downloads
2018-12-01 16:58:45 INFO POSTPROCESSOR :: Auto post processing task for /home/****/Downloads was added to the queue
2018-12-01 16:58:45 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 16:48:49 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /home/****/Downloads completed
2018-12-01 16:48:49 INFO POSTPROCESSOR-AUTO :: Successfully processed
2018-12-01 16:48:49 DEBUG POSTPROCESSOR-AUTO :: /home/****/Downloads : No processable items found in folder
2018-12-01 16:48:49 DEBUG POSTPROCESSOR-AUTO :: Processing folder /home/****/Downloads
2018-12-01 16:48:49 INFO POSTPROCESSOR-AUTO :: Processing /home/****/Downloads
2018-12-01 16:48:49 DEBUG POSTPROCESSOR-AUTO :: Processing in folder /home/****/Downloads
2018-12-01 16:48:49 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /home/****/Downloads
2018-12-01 16:48:44 INFO POSTPROCESSOR :: Auto post processing task for /home/****/Downloads was added to the queue
2018-12-01 16:48:44 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 16:38:49 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /home/****/Downloads completed
2018-12-01 16:38:49 INFO POSTPROCESSOR-AUTO :: Successfully processed
2018-12-01 16:38:49 DEBUG POSTPROCESSOR-AUTO :: /home/****/Downloads : No processable items found in folder
2018-12-01 16:38:48 DEBUG POSTPROCESSOR-AUTO :: Processing folder /home/****/Downloads
2018-12-01 16:38:48 INFO POSTPROCESSOR-AUTO :: Processing /home/****/Downloads
2018-12-01 16:38:48 DEBUG POSTPROCESSOR-AUTO :: Processing in folder /home/****/Downloads
2018-12-01 16:38:48 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /home/****/Downloads
2018-12-01 16:38:43 INFO POSTPROCESSOR :: Auto post processing task for /home/****/Downloads was added to the queue
2018-12-01 16:38:43 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 16:28:48 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /home/****/Downloads completed
2018-12-01 16:28:48 INFO POSTPROCESSOR-AUTO :: Successfully processed
2018-12-01 16:28:48 DEBUG POSTPROCESSOR-AUTO :: /home/****/Downloads : No processable items found in folder
2018-12-01 16:28:47 DEBUG POSTPROCESSOR-AUTO :: Processing folder /home/****/Downloads
2018-12-01 16:28:47 INFO POSTPROCESSOR-AUTO :: Processing /home/****/Downloads
2018-12-01 16:28:47 DEBUG POSTPROCESSOR-AUTO :: Processing in folder /home/****/Downloads
2018-12-01 16:28:47 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /home/****/Downloads
2018-12-01 16:28:43 INFO POSTPROCESSOR :: Auto post processing task for /home/****/Downloads was added to the queue
2018-12-01 16:28:43 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 16:18:46 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /home/****/Downloads completed
2018-12-01 16:18:46 INFO POSTPROCESSOR-AUTO :: Successfully processed
2018-12-01 16:18:46 DEBUG POSTPROCESSOR-AUTO :: /home/****/Downloads : No processable items found in folder
2018-12-01 16:18:46 DEBUG POSTPROCESSOR-AUTO :: Processing folder /home/****/Downloads
2018-12-01 16:18:46 INFO POSTPROCESSOR-AUTO :: Processing /home/****/Downloads
2018-12-01 16:18:46 DEBUG POSTPROCESSOR-AUTO :: Processing in folder /home/****/Downloads
2018-12-01 16:18:46 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /home/****/Downloads
2018-12-01 16:18:42 INFO POSTPROCESSOR :: Auto post processing task for /home/****/Downloads was added to the queue
2018-12-01 16:18:42 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 16:08:46 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /home/****/Downloads completed
2018-12-01 16:08:46 INFO POSTPROCESSOR-AUTO :: Successfully processed
2018-12-01 16:08:46 DEBUG POSTPROCESSOR-AUTO :: /home/****/Downloads : No processable items found in folder
2018-12-01 16:08:45 DEBUG POSTPROCESSOR-AUTO :: Processing folder /home/****/Downloads
2018-12-01 16:08:45 INFO POSTPROCESSOR-AUTO :: Processing /home/****/Downloads
2018-12-01 16:08:45 DEBUG POSTPROCESSOR-AUTO :: Processing in folder /home/****/Downloads
2018-12-01 16:08:45 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /home/****/Downloads
2018-12-01 16:08:41 INFO POSTPROCESSOR :: Auto post processing task for /home/****/Downloads was added to the queue
2018-12-01 16:08:41 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 15:58:45 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /home/****/Downloads completed
2018-12-01 15:58:45 INFO POSTPROCESSOR-AUTO :: Successfully processed
2018-12-01 15:58:45 DEBUG POSTPROCESSOR-AUTO :: /home/****/Downloads : No processable items found in folder
2018-12-01 15:58:44 DEBUG POSTPROCESSOR-AUTO :: Processing folder /home/****/Downloads
2018-12-01 15:58:44 INFO POSTPROCESSOR-AUTO :: Processing /home/****/Downloads
2018-12-01 15:58:44 DEBUG POSTPROCESSOR-AUTO :: Processing in folder /home/****/Downloads
2018-12-01 15:58:44 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /home/****/Downloads
2018-12-01 15:58:40 INFO POSTPROCESSOR :: Auto post processing task for /home/****/Downloads was added to the queue
2018-12-01 15:58:40 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 15:48:44 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /home/****/Downloads completed
2018-12-01 15:48:44 INFO POSTPROCESSOR-AUTO :: Successfully processed
2018-12-01 15:48:44 DEBUG POSTPROCESSOR-AUTO :: /home/****/Downloads : No processable items found in folder
2018-12-01 15:48:44 DEBUG POSTPROCESSOR-AUTO :: Processing folder /home/****/Downloads
2018-12-01 15:48:44 INFO POSTPROCESSOR-AUTO :: Processing /home/****/Downloads
2018-12-01 15:48:44 DEBUG POSTPROCESSOR-AUTO :: Processing in folder /home/****/Downloads
2018-12-01 15:48:44 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /home/****/Downloads
2018-12-01 15:48:40 INFO POSTPROCESSOR :: Auto post processing task for /home/****/Downloads was added to the queue
2018-12-01 15:48:40 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 15:38:44 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /home/****/Downloads completed
2018-12-01 15:38:44 INFO POSTPROCESSOR-AUTO :: Successfully processed
2018-12-01 15:38:44 DEBUG POSTPROCESSOR-AUTO :: /home/****/Downloads : No processable items found in folder
2018-12-01 15:38:43 DEBUG POSTPROCESSOR-AUTO :: Processing folder /home/****/Downloads
2018-12-01 15:38:43 INFO POSTPROCESSOR-AUTO :: Processing /home/****/Downloads
2018-12-01 15:38:43 DEBUG POSTPROCESSOR-AUTO :: Processing in folder /home/****/Downloads
2018-12-01 15:38:43 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /home/****/Downloads
2018-12-01 15:38:39 INFO POSTPROCESSOR :: Auto post processing task for /home/****/Downloads was added to the queue
2018-12-01 15:38:39 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 15:28:43 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /home/****/Downloads completed
2018-12-01 15:28:43 INFO POSTPROCESSOR-AUTO :: Successfully processed
2018-12-01 15:28:43 DEBUG POSTPROCESSOR-AUTO :: /home/****/Downloads : No processable items found in folder
2018-12-01 15:28:43 DEBUG POSTPROCESSOR-AUTO :: Processing folder /home/****/Downloads
2018-12-01 15:28:43 INFO POSTPROCESSOR-AUTO :: Processing /home/****/Downloads
2018-12-01 15:28:43 DEBUG POSTPROCESSOR-AUTO :: Processing in folder /home/****/Downloads
2018-12-01 15:28:42 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /home/****/Downloads
2018-12-01 15:28:38 INFO POSTPROCESSOR :: Auto post processing task for /home/****/Downloads was added to the queue
2018-12-01 15:28:38 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 15:18:43 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /home/****/Downloads completed
2018-12-01 15:18:43 INFO POSTPROCESSOR-AUTO :: Successfully processed
2018-12-01 15:18:43 DEBUG POSTPROCESSOR-AUTO :: /home/****/Downloads : No processable items found in folder
2018-12-01 15:18:42 DEBUG POSTPROCESSOR-AUTO :: Processing folder /home/****/Downloads
2018-12-01 15:18:42 INFO POSTPROCESSOR-AUTO :: Processing /home/****/Downloads
2018-12-01 15:18:42 DEBUG POSTPROCESSOR-AUTO :: Processing in folder /home/****/Downloads
2018-12-01 15:18:42 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /home/****/Downloads
2018-12-01 15:18:38 INFO POSTPROCESSOR :: Auto post processing task for /home/****/Downloads was added to the queue
2018-12-01 15:18:38 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 15:04:59 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-12-01 15:04:59 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 14:54:58 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-12-01 14:54:58 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 14:44:59 DEBUG POSTPROCESSOR-AUTO :: Processing folder /home/****/Downloads
2018-12-01 14:44:59 INFO POSTPROCESSOR-AUTO :: Processing /home/****/Downloads
2018-12-01 14:44:59 DEBUG POSTPROCESSOR-AUTO :: Processing in folder /home/****/Downloads
2018-12-01 14:44:59 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /home/****/Downloads
2018-12-01 14:44:57 INFO POSTPROCESSOR :: Auto post processing task for /home/****/Downloads was added to the queue
2018-12-01 14:44:57 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 14:35:32 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /home/****/Downloads completed
2018-12-01 14:35:32 INFO POSTPROCESSOR-AUTO :: Successfully processed
2018-12-01 14:35:32 DEBUG POSTPROCESSOR-AUTO :: /home/****/Downloads : No processable items found in folder
2018-12-01 14:34:57 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-12-01 14:34:57 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 14:24:56 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-12-01 14:24:56 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 14:14:55 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-12-01 14:14:55 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 14:04:55 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-12-01 14:04:55 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 13:54:54 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-12-01 13:54:54 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 13:44:53 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-12-01 13:44:53 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 13:34:53 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-12-01 13:34:53 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 13:24:53 DEBUG POSTPROCESSOR-AUTO :: Processing folder /home/****/Downloads
2018-12-01 13:24:53 INFO POSTPROCESSOR-AUTO :: Processing /home/****/Downloads
2018-12-01 13:24:53 DEBUG POSTPROCESSOR-AUTO :: Processing in folder /home/****/Downloads
2018-12-01 13:24:53 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /home/****/Downloads
2018-12-01 13:24:52 INFO POSTPROCESSOR :: Auto post processing task for /home/****/Downloads was added to the queue
2018-12-01 13:24:52 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 13:16:24 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /home/****/Downloads completed
2018-12-01 13:16:24 INFO POSTPROCESSOR-AUTO :: Successfully processed
2018-12-01 13:16:24 DEBUG POSTPROCESSOR-AUTO :: /home/****/Downloads : No processable items found in folder
2018-12-01 13:14:51 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-12-01 13:14:51 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 13:04:51 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-12-01 13:04:51 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 12:54:51 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-12-01 12:54:51 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 12:44:50 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-12-01 12:44:50 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 12:34:49 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-12-01 12:34:49 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 12:24:49 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-12-01 12:24:49 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 12:14:48 INFO POSTPROCESSOR :: /home/****/Downloads is already being processed right now, please wait until it completes before trying again
2018-12-01 12:14:48 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2018-12-01 12:04:52 DEBUG POSTPROCESSOR-AUTO :: Processing folder /home/****/Downloads
2018-12-01 12:04:52 INFO POSTPROCESSOR-AUTO :: Processing /home/****/Downloads
2018-12-01 12:04:52 DEBUG POSTPROCESSOR-AUTO :: Processing in folder /home/****/Downloads
2018-12-01 12:04:52 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /home/****/Downloads
2018-12-01 12:04:47 INFO POSTPROCESSOR :: Auto post processing task for /home/****/Downloads was added to the queue
2018-12-01 12:04:47 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
```

**Comment by WebSpider** [comment]
It would seem your postprocessor is restarting faster than it can finish processing.
Is your directory ``` /home/****/Downloads``` maybe filled with garbage, causing the postprocessor task to waste time by analyzing this time after time?

**Comment by kyuuk** [comment]
the directory was empty (or has one file in it), the only thing i can think of, is that while the PostPrecesssor thread while precessing the directory another file was added is the middle of that. (i'm trying to understand how the code works but don't know much of python)

**Comment by LachyTech** [comment]
I have been having this issue for quite some time as well, but it happens infrequently so it's hard to get logs for it. Restarting sickchill via the GUI doesn't resolve the issue, need to manually kill the process.

`2019-04-25 15:57:43 INFO POSTPROCESSOR :: /media/downloads/tv is already being processed right now, please wait until it completes before trying again
2019-04-25 15:57:43 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2019-04-25 15:47:42 INFO POSTPROCESSOR :: /media/downloads/tv is already being processed right now, please wait until it completes before trying again
2019-04-25 15:47:42 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2019-04-25 15:37:42 INFO POSTPROCESSOR :: /media/downloads/tv is already being processed right now, please wait until it completes before trying again
2019-04-25 15:37:42 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2019-04-25 15:27:42 INFO POSTPROCESSOR :: /media/downloads/tv is already being processed right now, please wait until it completes before trying again
2019-04-25 15:27:42 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2019-04-25 15:17:42 INFO POSTPROCESSOR :: /media/downloads/tv is already being processed right now, please wait until it completes before trying again
2019-04-25 15:17:42 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2019-04-25 15:07:41 INFO POSTPROCESSOR :: /media/downloads/tv is already being processed right now, please wait until it completes before trying again
2019-04-25 15:07:41 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2019-04-25 14:57:41 INFO POSTPROCESSOR :: /media/downloads/tv is already being processed right now, please wait until it completes before trying again
2019-04-25 14:57:41 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2019-04-25 14:47:40 INFO POSTPROCESSOR :: /media/downloads/tv is already being processed right now, please wait until it completes before trying again
2019-04-25 14:47:40 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2019-04-25 14:37:40 INFO POSTPROCESSOR :: /media/downloads/tv is already being processed right now, please wait until it completes before trying again
2019-04-25 14:37:40 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2019-04-25 14:27:40 INFO POSTPROCESSOR :: /media/downloads/tv is already being processed right now, please wait until it completes before trying again
2019-04-25 14:27:40 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2019-04-25 14:17:40 INFO POSTPROCESSOR :: /media/downloads/tv is already being processed right now, please wait until it completes before trying again
2019-04-25 14:17:40 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2019-04-25 14:07:39 INFO POSTPROCESSOR :: /media/downloads/tv is already being processed right now, please wait until it completes before trying again
2019-04-25 14:07:39 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2019-04-25 13:57:38 INFO POSTPROCESSOR :: /media/downloads/tv is already being processed right now, please wait until it completes before trying again
2019-04-25 13:57:38 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2019-04-25 13:47:38 INFO POSTPROCESSOR :: /media/downloads/tv is already being processed right now, please wait until it completes before trying again
2019-04-25 13:47:38 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2019-04-25 13:37:38 INFO POSTPROCESSOR :: /media/downloads/tv is already being processed right now, please wait until it completes before trying again
2019-04-25 13:37:38 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2019-04-25 13:27:38 INFO POSTPROCESSOR :: /media/downloads/tv is already being processed right now, please wait until it completes before trying again
2019-04-25 13:27:38 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2019-04-25 13:17:37 INFO POSTPROCESSOR :: /media/downloads/tv is already being processed right now, please wait until it completes before trying again
2019-04-25 13:17:37 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2019-04-25 13:07:36 INFO POSTPROCESSOR :: /media/downloads/tv is already being processed right now, please wait until it completes before trying again
2019-04-25 13:07:36 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2019-04-25 12:57:36 INFO POSTPROCESSOR :: /media/downloads/tv is already being processed right now, please wait until it completes before trying again
2019-04-25 12:57:36 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2019-04-25 12:47:36 INFO POSTPROCESSOR :: /media/downloads/tv is already being processed right now, please wait until it completes before trying again
2019-04-25 12:47:36 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR`
