### ISSUE TITLE
unable to update since last update went out

### ISSUE THREAD

**Issue by theskillwithin** [SickChill/SickChill#5582]
There is a newer version available (you're 1 commit behind) — Update Now

I click update and the browser just keeps spinning polling get_messages in the network panel.   wait for 20 min and its still doing the same thing.   i refresh and it takes me back to home page where still 1 commit behind.

nothing appears in logs

**Comment by jcamm3** [comment]
I'm having the same issue.  Error log shows:

2019-07-27 09:37:03 CHECKVERSION :: [81652b0] git pull -f origin master returned : From https://github.com/SickChill/SickChill
* branch master -> FETCH_HEAD
Updating 81652b0..1ed3156
error: Unable to create '/app/sickchill/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.

**Comment by jcamm3** [comment]
I've removed the lock file.  Same error.  Did a hard reset 'git --hard origin/master'.  Same error.

**Comment by theskillwithin** [comment]
still no luck on this

**Comment by WebSpider** [comment]
Your lock file or entire directory may be owned by another user as the one SickChill runs as. Please check ownerships.

**Comment by theskillwithin** [comment]
@WebSpider do you mean yarn.lock file?

```
➜  sickchill ll -a
total 468K
drwxr-xr-x 1 admin admin  780 Jul 30 20:06 .
drwxrwxr-x 1 root  root   414 Aug 14 17:58 ..
drwxr-xr-x 1 admin admin  420 Aug 15 19:48 app-config
-rw-rw-r-- 1 admin admin 2.7K Jun 28 12:13 .appveyor.yml
-rw-rw-r-- 1 admin admin  848 Jun 28 12:13 bower.json
-rw-rw-r-- 1 admin admin   38 Jun 28 12:13 .bowerrc
-rw-rw-r-- 1 admin admin   25 Jun 28 12:13 .checkignore
-rw-rw-r-- 1 admin admin 4.1K Jun 28 12:13 .codecov.yml
-rw-r--r-- 1 admin admin  588 Nov  8  2018 config.xml
drwxr-xr-x 1 admin admin   78 Jul 30 20:06 contrib
-rw-rw-r-- 1 admin admin  35K Jun 28 12:13 COPYING.txt
-rw-rw-r-- 1 admin admin  224 Jun 28 12:13 crowdin.yaml
-rw-rw-r-- 1 admin admin  292 Jun 28 12:13 docker-compose.yaml
-rw-rw-r-- 1 admin admin  655 Jun 28 12:13 Dockerfile
-rw-rw-r-- 1 admin admin   13 Jun 28 12:13 .dockerignore
-rw-rw-r-- 1 admin admin  490 Jun 28 12:13 .editorconfig
-rw-r--r-- 1 admin admin  302 Nov  8  2018 fvapp-sickchill.service
-rw-rw-r-- 1 admin admin 1.6K Jun 28 12:13 .gitattributes
drwxr-xr-x 1 admin admin  130 Jul 30 20:06 .github
-rw-rw-r-- 1 admin admin 1.1K Jun 28 12:13 .gitignore
-rw-rw-r-- 1 admin admin  20K Jun 28 12:13 Gruntfile.js
drwxr-xr-x 1 admin admin   10 Nov  9  2018 gui
drwxr-xr-x 1 admin admin 3.3K Jul 30 20:06 lib
drwxr-xr-x 1 admin admin  414 Jun 27 19:16 locale
-rw-r--r-- 1 admin admin  17K Nov  8  2018 logo.png
-rw-rw-r-- 1 admin admin  141 Jun 28 12:13 nose.cfg
-rw-rw-r-- 1 admin admin 2.5K Jun 28 12:13 package.json
-rw-rw-r-- 1 admin admin 5.2K Jun 28 12:13 readme.md
drwxr-xr-x 1 admin admin   86 Jun 27 19:16 requirements
drwxr-xr-x 1 admin admin  212 Jun 27 19:16 runscripts
-rw-rw-r-- 1 admin admin  985 Jun 28 12:13 setup.cfg
-rw-rw-r-- 1 admin admin 2.3K Jun 28 12:13 setup.py
drwxr-xr-x 1 admin admin 3.0K Jun 27 19:17 sickbeard
-rwxrwxr-x 1 admin admin  22K Jun 28 12:13 SickBeard.py
drwxr-xr-x 1 admin admin  148 Jun 27 19:17 sickchill
-rw-rw-r-- 1 admin admin  441 Jun 28 12:13 .snyk
drwxr-xr-x 1 admin admin   54 Jul 30 20:06 sr-update
drwxr-xr-x 1 admin admin  882 Jun 27 19:16 tests
-rw-rw-r-- 1 admin admin 2.0K Jun 28 12:13 tox.ini
-rw-rw-r-- 1 admin admin 1.6K Jun 28 12:13 .travis.yml
-rw-rw-r-- 1 admin admin 272K Jun 28 12:13 yarn.lock
```

**Comment by WebSpider** [comment]
Hi!
No, I mean the .git/index.lock

**Comment by jcamm3** [comment]
I'm running in a docker container - https://hub.docker.com/u/sickchill

-rwxrwxr-x    1 root     root           100 Aug 16 07:11 FETCH_HEAD
-rwxrwxr-x    1 root     root            23 Jan  6  2019 HEAD
-rw-r--r--    1 root     root            41 Aug 16 07:11 ORIG_HEAD
drwxrwxr-x    3 root     root          4096 Jul 27 09:34 branches
-rwxrwxr-x    1 root     root           277 Aug 16 07:11 config
-rwxrwxr-x    1 root     root            73 Jan  6  2019 description
drwxrwxr-x    2 root     root          4096 Aug  2 08:00 hooks
-rwxrwxr-x    1 root     root        575245 Jun 27 04:18 index
-rw-r--r--    1 root     root             0 Aug  2 09:03 index.lock
drwxrwxr-x    2 root     root          4096 Aug  2 08:00 info
drwxrwxr-x    4 root     root          4096 Apr  7 22:29 logs
drwxrwxr-x  113 root     root          4096 Aug  2 08:00 objects
-rwxrwxr-x    1 root     root           107 Jan  6  2019 packed-refs
drwxrwxr-x    8 root     root          4096 Apr  7 22:29 refs
-rwxrwxr-x    1 root     root            41 Jan  6  2019 shallow

**Comment by theskillwithin** [comment]
@WebSpider strange i don't have a .git folder

**Comment by WebSpider** [comment]
@jcamm3 if ur in a docker container, just update the container version. Should be fine.

**Comment by jcamm3** [comment]
@WebSpider Thanks for the information.  How do I update the container properly so I don't loose the existing settings?  current: sickshill/sickchill:latest
Appreciate the help.  Still learning the docker, etc.  I did find this info on linuxservers version but want to make sure I get it right..  https://github.com/linuxserver/docker-sickchill

**Comment by WebSpider** [comment]
If you have the volumes setup (and you normally would), running 'docker pull sickchill/sickchill:latest should update

**Comment by jcamm3** [comment]
@WebSpider Thanks.  Updated to the current.  I removed the .lock file after the update.  All working now.  Appreciate it!

**Comment by WebSpider** [comment]
Should be fixed in last release

**Comment by HazMatt69** [comment]
I have a similar issue, the last update I have is Commit: e094759640ca61c5c033bf1ff9d33bc7fc1ba857
Version: v2019.06.28-1 but as the last Commit is the same (e094759640ca61c5c033bf1ff9d33bc7fc1ba857), sickchill won't update to latest version.
Thanks for your help!

**Comment by jcamm3** [comment]
I'm having a similar issue updating to the most current commit.  Running a docker and have updated it to the latest version.

from log:
2019-09-09 10:57:42 INFO CHECKVERSION :: Update failed!
AA None
AA remove the file manually to continue.
AA may have crashed in this repository earlier:
AA are terminated then try again. If it still fails, a git process
AA an editor opened by 'git commit'. Please make sure all processes
AA Another git process seems to be running in this repository, e.g.
AA error: Unable to create '/app/sickchill/.git/index.lock': File exists.
AA Updating 1ed3156..e094759
AA * branch master -> FETCH_HEAD
2019-09-09 10:57:42 ERROR CHECKVERSION :: [1ed3156] git pull -f origin master returned : From https://github.com/SickChill/SickChill
AA remove the file manually to continue.
AA may have crashed in this repository earlier:
AA are terminated then try again. If it still fails, a git process
AA an editor opened by 'git commit'. Please make sure all processes
AA Another git process seems to be running in this repository, e.g.
2019-09-09 10:57:37 WARNING CHECKVERSION :: git reset --hard returned : (128) fatal: Unable to create '/app/sickchill/.git/index.lock': File exists.
2019-09-09 10:57:37 INFO CHECKVERSION :: Config backup successful, updating...
2019-09-09 10:56:53 INFO CHECKVERSION :: Config backup in progress...
2019-09-09 10:56:52 INFO CHECKVERSION :: New update found for SickChill, starting auto-updater ...
2019-09-09 10:56:52 INFO TORNADO :: Starting SickChill on http://0.0.0.0:8081/



running 'sudo docker pull sickchill/sickchill:latest' shows:
latest: Pulling from sickchill/sickchill
Digest: sha256:d67e4fd965b6e2230a819b1743d8e0138985579512f00d2bd78e62cfae69ed25
Status: Image is up to date for sickchill/sickchill:latest

**Comment by jcamm3** [comment]
also, I removed the index.lock file.  Still no change.

**Comment by theetallest** [comment]
I to am having this issue.  I went to pull the latest file and it appeared to pull down an updated image but alas I am still seeing this "There is a newer version available (you're 8 commit behind) — Update Now"    I am portainer that has watchtower installed to make sure everything every thing stays up today.   I could not find/locate any index.lock file on my system at all both in and out of the container.
