### ISSUE TITLE
Some "Help & Info" links are pointing to a 404 on pip installs

### ISSUE THREAD

**Issue by stynoo** [SickChill/SickChill#6788]
Somewhat related to #6787

SickChill Info:
Branch: pip
Commit: c9a015b4b90ef673c57a79dc600e3fa183576013
Version: 2020.9.21.post2
Database Version: 44.2
  Python Version:3.8.5 (default, Aug 22 2020, 01:15:22) [Clang 8.0.0 (tags/RELEASE_800/final 356365)]
  SSL Version:OpenSSL 1.0.2s-freebsd 28 May 2019
  OS:FreeBSD-11.3-RELEASE-p11-amd64-64bit-ELF
  Locale:en_US.UTF-8

Branch link is:
`https://github.com/SickChill/SickChill/tree/pip`
Link suggestion, could be:
`https://pypi.org/project/sickchill`

Version link is:
`https://github.com/SickChill/SickChill/releases/tag/2020.9.21.post2`
Should be:
`https://github.com/SickChill/SickChill/releases/tag/v2020.09.21-2`

**Comment by stynoo** [comment]
@miigotu : first of all, thanks for the work you put into this, much appreciated! 
Do you mind if I keep on posting these -minor- issues like this or would you like to see them reported differently?  
(I tried to figure it out myself but its the first time I ran into Mako.)

**Comment by miigotu** [comment]
Generally I would prefer pinging me on discord (or slack/telegram/IRC), even for more serious issues.

I hate having tons of issues open, and that can keep issues to a minimum on here and I can fix them rather quick.

Either way, as long as it isn't coming across as complaining and excessive nitpicking it works either place. (Sorry, just had some self entitled people really tick me off a bit ago lol)

I will fix this as soon as the baby goes back down, it's just an oversight and easily fixed.

**Comment by stynoo** [comment]
> Either way, as long as it isn't coming across as complaining and excessive nitpicking it works either place. 
Yeah, that's what I am trying to avoid, especially when logging minor issues with just a few lines of text. ;) 
I'll ping you on Discord (if there is a) next time.

**Comment by miigotu** [comment]
Fixed

**Comment by miigotu** [comment]
Let me know if that isn't correct because it was all blind code and I did not test it.

**Comment by stynoo** [comment]
A am afraid you didn't intended it to look like this? 
![image](https://user-images.githubusercontent.com/17745813/93887137-97f03180-fce6-11ea-9570-4afa3c0750f7.png)

**Comment by miigotu** [comment]
There is a bug there, not bothering with it anymore today, 9:22 am already.

**Comment by stynoo** [comment]
nn & thx!

Your latest commit today fixed a bit, just the commit part is still missing.
![image](https://user-images.githubusercontent.com/17745813/93892242-9b86b700-fcec-11ea-81a6-e098517afede.png)

**Comment by miigotu** [comment]
For pip it does not know what commit it is, it only knows the version installed by pip.
